/*
 * ABI shim for the MicroTrust "beanpod" keymaster HAL on MT6785 (begonia).
 *
 * BACKGROUND
 * ----------
 * The stock vendor blobs
 *     vendor/bin/hw/android.hardware.keymaster@4.0-service.beanpod
 *     vendor/lib64/libkeymaster4.so
 *     vendor/lib64/libkeymaster4support.so
 * declare a DT_NEEDED entry for "libshim_beanpod.so" and resolve a handful of
 * libkeymaster_messages symbols from it. Those symbols were generated by an
 * older keymaster ABI than the one shipped in the current recovery tree, so
 * without this shim the beanpod keymaster cannot start and hardware
 * wrapped-key FBE decryption fails.
 *
 * The symbol list below was derived from the UND entries in the real vendor
 * binaries with:
 *     readelf -sW libkeymaster4.so | grep UND
 *
 * Only the out-of-line destructors and the SetKeyMaterial() family need to be
 * provided here; everything else (AndroidKeymaster, AuthorizationSet, Buffer,
 * Deserialize, ...) comes from the libkeymaster_messages.so that recovery
 * builds, whose ABI is compatible.
 */

#include <keymaster/android_keymaster_messages.h>

#include <cstdint>
#include <cstring>

namespace {

template <typename T>
inline void assign_key_material(T* req, const uint8_t* key, size_t len) {
    req->key_data = keymaster::KeymasterKeyBlob(key, len);
}

inline void assign_wrapped(keymaster::ImportWrappedKeyRequest* req,
                           const uint8_t* data, size_t len, uint32_t which) {
    switch (which) {
        case 0:
            req->wrapped_key_data = keymaster::KeymasterKeyBlob(data, len);
            break;
        case 1:
            req->wrapping_key_data = keymaster::KeymasterKeyBlob(data, len);
            break;
        case 2:
            req->masking_key_data = keymaster::KeymasterKeyBlob(data, len);
            break;
        default:
            break;
    }
}

}  // namespace

extern "C" {

/* ------------------------------------------------------------------ */
/* Out-of-line destructors (D1 = complete object, D2 = deleting)      */
/* ------------------------------------------------------------------ */

void _ZN9keymaster19GenerateKeyResponseD1Ev() {}
void _ZN9keymaster19GenerateKeyResponseD2Ev() {}
void _ZN9keymaster17AttestKeyResponseD1Ev() {}
void _ZN9keymaster17AttestKeyResponseD2Ev() {}
void _ZN9keymaster18UpgradeKeyResponseD1Ev() {}
void _ZN9keymaster18UpgradeKeyResponseD2Ev() {}
void _ZN9keymaster16AttestKeyRequestD1Ev() {}
void _ZN9keymaster16AttestKeyRequestD2Ev() {}
void _ZN9keymaster17UpgradeKeyRequestD1Ev() {}
void _ZN9keymaster17UpgradeKeyRequestD2Ev() {}
void _ZN9keymaster28GetKeyCharacteristicsRequestD1Ev() {}
void _ZN9keymaster28GetKeyCharacteristicsRequestD2Ev() {}
void _ZN9keymaster16AuthorizationSetD1Ev() {}
void _ZN9keymaster16AuthorizationSetD2Ev() {}

/* ------------------------------------------------------------------ */
/* SetKeyMaterial(const void*, size_t) overloads                      */
/* ------------------------------------------------------------------ */

void _ZN9keymaster16ImportKeyRequest14SetKeyMaterialEPKvm(
        keymaster::ImportKeyRequest* t, const uint8_t* k, size_t l) {
    assign_key_material(t, k, l);
}

void _ZN9keymaster16ExportKeyRequest14SetKeyMaterialEPKvm(
        keymaster::ExportKeyRequest* t, const uint8_t* k, size_t l) {
    assign_key_material(t, k, l);
}

void _ZN9keymaster16AttestKeyRequest14SetKeyMaterialEPKvm(
        keymaster::AttestKeyRequest* t, const uint8_t* k, size_t l) {
    assign_key_material(t, k, l);
}

void _ZN9keymaster16DeleteKeyRequest14SetKeyMaterialEPKvm(
        keymaster::DeleteKeyRequest* t, const uint8_t* k, size_t l) {
    assign_key_material(t, k, l);
}

void _ZN9keymaster17UpgradeKeyRequest14SetKeyMaterialEPKvm(
        keymaster::UpgradeKeyRequest* t, const uint8_t* k, size_t l) {
    assign_key_material(t, k, l);
}

void _ZN9keymaster21BeginOperationRequest14SetKeyMaterialEPKvm(
        keymaster::BeginOperationRequest* t, const uint8_t* k, size_t l) {
    assign_key_material(t, k, l);
}

void _ZN9keymaster28GetKeyCharacteristicsRequest14SetKeyMaterialEPKvm(
        keymaster::GetKeyCharacteristicsRequest* t, const uint8_t* k, size_t l) {
    assign_key_material(t, k, l);
}

/* ------------------------------------------------------------------ */
/* ImportWrappedKeyRequest setters                                    */
/* ------------------------------------------------------------------ */

void _ZN9keymaster23ImportWrappedKeyRequest18SetWrappedMaterialEPKvm(
        keymaster::ImportWrappedKeyRequest* t, const uint8_t* k, size_t l) {
    assign_wrapped(t, k, l, 0);
}

void _ZN9keymaster23ImportWrappedKeyRequest19SetWrappingMaterialEPKvm(
        keymaster::ImportWrappedKeyRequest* t, const uint8_t* k, size_t l) {
    assign_wrapped(t, k, l, 1);
}

void _ZN9keymaster23ImportWrappedKeyRequest21SetMaskingKeyMaterialEPKvm(
        keymaster::ImportWrappedKeyRequest* t, const uint8_t* k, size_t l) {
    assign_wrapped(t, k, l, 2);
}

}  /* extern "C" */